generate_features: true
preprocess: false
train_model: false
atom_types:
 - Si
 - O

descriptor:
  type: symmetry_function
  params:
    Si: params_Si
    O: params_O
  valid_rate: 0.1
  remain_pickle: True
  compress_outcar: True
  save_to_pickle: False
  save_directory: data

neural_network:
  pca: true
  pca_whiten: true
  weight_initializer:
    type: he normal  
  save_criteria: []
  batch_size: 20
  continue: false
  double_precision: true
  energy_coeff: 1.0
  force_coeff:  0.1
  full_batch: false
  cache: false
  learning_rate: 0.0001
  loss_scale: 1.0
  acti_func: tanh
  method: Adam
  nodes: 30-30
  optimizer: {}
  print_structure_rmse: true
  regularization:
    type: l2
    params:
      coeff: 1.0e-8
  save_interval: 200
  show_interval: 200
  test: false
  total_iteration: 50000
  train: true
  use_force: true
  use_stress: true
  intra_op_parallelism_threads: 20
  inter_op_parallelism_threads: 2
